#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : cri-o
Version  : 1.15.2
Release  : 63
URL      : https://github.com/cri-o/cri-o/archive/v1.15.2.tar.gz
Source0  : https://github.com/cri-o/cri-o/archive/v1.15.2.tar.gz
Source1  : cri-o.tmpfiles
Summary  : Builds Dockerfile using the Docker client
Group    : Development/Tools
License  : Apache-2.0 BSD-2-Clause BSD-2-Clause-FreeBSD BSD-3-Clause CC-BY-SA-4.0 GPL-3.0 ISC MIT MPL-2.0 MPL-2.0-no-copyleft-exception
Requires: cri-o-bin = %{version}-%{release}
Requires: cri-o-config = %{version}-%{release}
Requires: cri-o-data = %{version}-%{release}
Requires: cri-o-libexec = %{version}-%{release}
Requires: cri-o-license = %{version}-%{release}
Requires: cri-o-man = %{version}-%{release}
Requires: cri-o-services = %{version}-%{release}
BuildRequires : btrfs-progs-dev
BuildRequires : buildreq-golang
BuildRequires : golang-github-cpuguy83-go-md2man
BuildRequires : libassuan-dev
BuildRequires : libgpg-error-dev
BuildRequires : libgpg-error-extras
BuildRequires : libgpg-error-staticdev
BuildRequires : pkgconfig(devmapper)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(libseccomp)
Patch1: 0001-include-usr-share-defaults-in-conf-file-search.patch
Patch2: 0003-Update-default-crio.conf-file-for-Clear-Linux.patch
Patch3: 0004-Add-bin-subfolder.patch
Patch4: 0005-add-default-signature-verification-policy-file.patch
Patch5: 0007-Update-Makefile-to-find-md2man.patch

%description
Builds Dockerfile using the Docker client

%package bin
Summary: bin components for the cri-o package.
Group: Binaries
Requires: cri-o-data = %{version}-%{release}
Requires: cri-o-libexec = %{version}-%{release}
Requires: cri-o-config = %{version}-%{release}
Requires: cri-o-license = %{version}-%{release}
Requires: cri-o-services = %{version}-%{release}

%description bin
bin components for the cri-o package.


%package config
Summary: config components for the cri-o package.
Group: Default

%description config
config components for the cri-o package.


%package data
Summary: data components for the cri-o package.
Group: Data

%description data
data components for the cri-o package.


%package libexec
Summary: libexec components for the cri-o package.
Group: Default
Requires: cri-o-config = %{version}-%{release}
Requires: cri-o-license = %{version}-%{release}

%description libexec
libexec components for the cri-o package.


%package license
Summary: license components for the cri-o package.
Group: Default

%description license
license components for the cri-o package.


%package man
Summary: man components for the cri-o package.
Group: Default

%description man
man components for the cri-o package.


%package services
Summary: services components for the cri-o package.
Group: Systemd services

%description services
services components for the cri-o package.


%prep
%setup -q -n cri-o-1.15.2
%patch1 -p1
%patch2 -p1
%patch3 -p1
%patch4 -p1
%patch5 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1570719591
export GCC_IGNORE_WERROR=1
export GOPROXY=file:///usr/share/goproxy
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
make  %{?_smp_mflags}


%install
export SOURCE_DATE_EPOCH=1570719591
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/cri-o
cp LICENSE %{buildroot}/usr/share/package-licenses/cri-o/LICENSE
cp logo/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/logo_LICENSE
cp vendor/github.com/Azure/go-ansiterm/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_Azure_go-ansiterm_LICENSE
cp vendor/github.com/BurntSushi/toml/COPYING %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_BurntSushi_toml_COPYING
cp vendor/github.com/Microsoft/go-winio/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_Microsoft_go-winio_LICENSE
cp vendor/github.com/Microsoft/go-winio/archive/tar/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_Microsoft_go-winio_archive_tar_LICENSE
cp vendor/github.com/Microsoft/hcsshim/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_Microsoft_hcsshim_LICENSE
cp vendor/github.com/OpenPeeDeeP/depguard/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_OpenPeeDeeP_depguard_LICENSE
cp vendor/github.com/VividCortex/ewma/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_VividCortex_ewma_LICENSE
cp vendor/github.com/beorn7/perks/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_beorn7_perks_LICENSE
cp vendor/github.com/blang/semver/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_blang_semver_LICENSE
cp vendor/github.com/checkpoint-restore/go-criu/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_checkpoint-restore_go-criu_LICENSE
cp vendor/github.com/containerd/console/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_containerd_console_LICENSE
cp vendor/github.com/containerd/containerd/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_containerd_containerd_LICENSE
cp vendor/github.com/containerd/continuity/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_containerd_continuity_LICENSE
cp vendor/github.com/containerd/fifo/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_containerd_fifo_LICENSE
cp vendor/github.com/containerd/go-runc/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_containerd_go-runc_LICENSE
cp vendor/github.com/containerd/project/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_containerd_project_LICENSE
cp vendor/github.com/containerd/ttrpc/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_containerd_ttrpc_LICENSE
cp vendor/github.com/containerd/typeurl/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_containerd_typeurl_LICENSE
cp vendor/github.com/containernetworking/cni/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_containernetworking_cni_LICENSE
cp vendor/github.com/containernetworking/plugins/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_containernetworking_plugins_LICENSE
cp vendor/github.com/containers/buildah/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_containers_buildah_LICENSE
cp vendor/github.com/containers/image/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_containers_image_LICENSE
cp vendor/github.com/containers/libpod/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_containers_libpod_LICENSE
cp vendor/github.com/containers/libpod/pkg/kubeutils/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_containers_libpod_pkg_kubeutils_LICENSE
cp vendor/github.com/containers/psgo/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_containers_psgo_LICENSE
cp vendor/github.com/containers/storage/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_containers_storage_LICENSE
cp vendor/github.com/containers/storage/NOTICE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_containers_storage_NOTICE
cp vendor/github.com/coreos/go-iptables/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_coreos_go-iptables_LICENSE
cp vendor/github.com/coreos/go-systemd/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_coreos_go-systemd_LICENSE
cp vendor/github.com/coreos/pkg/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_coreos_pkg_LICENSE
cp vendor/github.com/cpuguy83/go-md2man/LICENSE.md %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_cpuguy83_go-md2man_LICENSE.md
cp vendor/github.com/cri-o/ocicni/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_cri-o_ocicni_LICENSE
cp vendor/github.com/cyphar/filepath-securejoin/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_cyphar_filepath-securejoin_LICENSE
cp vendor/github.com/davecgh/go-spew/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_davecgh_go-spew_LICENSE
cp vendor/github.com/docker/distribution/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_docker_distribution_LICENSE
cp vendor/github.com/docker/docker-credential-helpers/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_docker_docker-credential-helpers_LICENSE
cp vendor/github.com/docker/docker/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_docker_docker_LICENSE
cp vendor/github.com/docker/docker/NOTICE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_docker_docker_NOTICE
cp vendor/github.com/docker/docker/pkg/symlink/LICENSE.APACHE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_docker_docker_pkg_symlink_LICENSE.APACHE
cp vendor/github.com/docker/docker/pkg/symlink/LICENSE.BSD %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_docker_docker_pkg_symlink_LICENSE.BSD
cp vendor/github.com/docker/go-connections/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_docker_go-connections_LICENSE
cp vendor/github.com/docker/go-metrics/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_docker_go-metrics_LICENSE
cp vendor/github.com/docker/go-metrics/LICENSE.docs %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_docker_go-metrics_LICENSE.docs
cp vendor/github.com/docker/go-units/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_docker_go-units_LICENSE
cp vendor/github.com/docker/libnetwork/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_docker_libnetwork_LICENSE
cp vendor/github.com/docker/libtrust/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_docker_libtrust_LICENSE
cp vendor/github.com/docker/spdystream/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_docker_spdystream_LICENSE
cp vendor/github.com/docker/spdystream/LICENSE.docs %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_docker_spdystream_LICENSE.docs
cp vendor/github.com/emicklei/go-restful/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_emicklei_go-restful_LICENSE
cp vendor/github.com/etcd-io/bbolt/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_etcd-io_bbolt_LICENSE
cp vendor/github.com/fatih/color/LICENSE.md %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_fatih_color_LICENSE.md
cp vendor/github.com/fsnotify/fsnotify/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_fsnotify_fsnotify_LICENSE
cp vendor/github.com/fsouza/go-dockerclient/DOCKER-LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_fsouza_go-dockerclient_DOCKER-LICENSE
cp vendor/github.com/fsouza/go-dockerclient/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_fsouza_go-dockerclient_LICENSE
cp vendor/github.com/ghodss/yaml/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_ghodss_yaml_LICENSE
cp vendor/github.com/go-critic/go-critic/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_go-critic_go-critic_LICENSE
cp vendor/github.com/go-lintpack/lintpack/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_go-lintpack_lintpack_LICENSE
cp vendor/github.com/go-toolsmith/astcast/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_go-toolsmith_astcast_LICENSE
cp vendor/github.com/go-toolsmith/astcopy/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_go-toolsmith_astcopy_LICENSE
cp vendor/github.com/go-toolsmith/astequal/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_go-toolsmith_astequal_LICENSE
cp vendor/github.com/go-toolsmith/astfmt/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_go-toolsmith_astfmt_LICENSE
cp vendor/github.com/go-toolsmith/astp/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_go-toolsmith_astp_LICENSE
cp vendor/github.com/go-toolsmith/strparse/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_go-toolsmith_strparse_LICENSE
cp vendor/github.com/go-toolsmith/typep/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_go-toolsmith_typep_LICENSE
cp vendor/github.com/go-zoo/bone/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_go-zoo_bone_LICENSE
cp vendor/github.com/gobwas/glob/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_gobwas_glob_LICENSE
cp vendor/github.com/godbus/dbus/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_godbus_dbus_LICENSE
cp vendor/github.com/gogo/protobuf/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_gogo_protobuf_LICENSE
cp vendor/github.com/golang/groupcache/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_golang_groupcache_LICENSE
cp vendor/github.com/golang/mock/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_golang_mock_LICENSE
cp vendor/github.com/golang/protobuf/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_golang_protobuf_LICENSE
cp vendor/github.com/golangci/check/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_golangci_check_LICENSE
cp vendor/github.com/golangci/dupl/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_golangci_dupl_LICENSE
cp vendor/github.com/golangci/errcheck/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_golangci_errcheck_LICENSE
cp vendor/github.com/golangci/go-misc/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_golangci_go-misc_LICENSE
cp vendor/github.com/golangci/go-tools/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_golangci_go-tools_LICENSE
cp vendor/github.com/golangci/go-tools/lint/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_golangci_go-tools_lint_LICENSE
cp vendor/github.com/golangci/go-tools/ssa/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_golangci_go-tools_ssa_LICENSE
cp vendor/github.com/golangci/goconst/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_golangci_goconst_LICENSE
cp vendor/github.com/golangci/gocyclo/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_golangci_gocyclo_LICENSE
cp vendor/github.com/golangci/gofmt/gofmt/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_golangci_gofmt_gofmt_LICENSE
cp vendor/github.com/golangci/gofmt/goimports/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_golangci_gofmt_goimports_LICENSE
cp vendor/github.com/golangci/golangci-lint/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_golangci_golangci-lint_LICENSE
cp vendor/github.com/golangci/gosec/LICENSE.txt %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_golangci_gosec_LICENSE.txt
cp vendor/github.com/golangci/ineffassign/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_golangci_ineffassign_LICENSE
cp vendor/github.com/golangci/lint-1/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_golangci_lint-1_LICENSE
cp vendor/github.com/golangci/maligned/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_golangci_maligned_LICENSE
cp vendor/github.com/golangci/misspell/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_golangci_misspell_LICENSE
cp vendor/github.com/golangci/prealloc/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_golangci_prealloc_LICENSE
cp vendor/github.com/golangci/revgrep/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_golangci_revgrep_LICENSE
cp vendor/github.com/golangci/unconvert/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_golangci_unconvert_LICENSE
cp vendor/github.com/google/go-cmp/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_google_go-cmp_LICENSE
cp vendor/github.com/google/gofuzz/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_google_gofuzz_LICENSE
cp vendor/github.com/google/renameio/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_google_renameio_LICENSE
cp vendor/github.com/google/uuid/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_google_uuid_LICENSE
cp vendor/github.com/googleapis/gnostic/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_googleapis_gnostic_LICENSE
cp vendor/github.com/gorilla/mux/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_gorilla_mux_LICENSE
cp vendor/github.com/gostaticanalysis/analysisutil/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_gostaticanalysis_analysisutil_LICENSE
cp vendor/github.com/hashicorp/errwrap/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_hashicorp_errwrap_LICENSE
cp vendor/github.com/hashicorp/go-multierror/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_hashicorp_go-multierror_LICENSE
cp vendor/github.com/hashicorp/go-version/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_hashicorp_go-version_LICENSE
cp vendor/github.com/hashicorp/golang-lru/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_hashicorp_golang-lru_LICENSE
cp vendor/github.com/hashicorp/hcl/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_hashicorp_hcl_LICENSE
cp vendor/github.com/hpcloud/tail/LICENSE.txt %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_hpcloud_tail_LICENSE.txt
cp vendor/github.com/hpcloud/tail/ratelimiter/Licence %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_hpcloud_tail_ratelimiter_Licence
cp vendor/github.com/ijc/Gotty/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_ijc_Gotty_LICENSE
cp vendor/github.com/imdario/mergo/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_imdario_mergo_LICENSE
cp vendor/github.com/inconshreveable/mousetrap/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_inconshreveable_mousetrap_LICENSE
cp vendor/github.com/ishidawataru/sctp/GO_LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_ishidawataru_sctp_GO_LICENSE
cp vendor/github.com/ishidawataru/sctp/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_ishidawataru_sctp_LICENSE
cp vendor/github.com/json-iterator/go/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_json-iterator_go_LICENSE
cp vendor/github.com/kisielk/gotool/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_kisielk_gotool_LICENSE
cp vendor/github.com/klauspost/compress/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_klauspost_compress_LICENSE
cp vendor/github.com/klauspost/compress/snappy/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_klauspost_compress_snappy_LICENSE
cp vendor/github.com/klauspost/compress/zstd/internal/xxhash/LICENSE.txt %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_klauspost_compress_zstd_internal_xxhash_LICENSE.txt
cp vendor/github.com/klauspost/cpuid/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_klauspost_cpuid_LICENSE
cp vendor/github.com/klauspost/pgzip/GO_LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_klauspost_pgzip_GO_LICENSE
cp vendor/github.com/klauspost/pgzip/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_klauspost_pgzip_LICENSE
cp vendor/github.com/konsorten/go-windows-terminal-sequences/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_konsorten_go-windows-terminal-sequences_LICENSE
cp vendor/github.com/kr/pty/License %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_kr_pty_License
cp vendor/github.com/lithammer/dedent/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_lithammer_dedent_LICENSE
cp vendor/github.com/magiconair/properties/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_magiconair_properties_LICENSE
cp vendor/github.com/mattn/go-colorable/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_mattn_go-colorable_LICENSE
cp vendor/github.com/mattn/go-isatty/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_mattn_go-isatty_LICENSE
cp vendor/github.com/mattn/go-shellwords/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_mattn_go-shellwords_LICENSE
cp vendor/github.com/matttproud/golang_protobuf_extensions/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_matttproud_golang_protobuf_extensions_LICENSE
cp vendor/github.com/mistifyio/go-zfs/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_mistifyio_go-zfs_LICENSE
cp vendor/github.com/mitchellh/go-homedir/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_mitchellh_go-homedir_LICENSE
cp vendor/github.com/mitchellh/mapstructure/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_mitchellh_mapstructure_LICENSE
cp vendor/github.com/modern-go/concurrent/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_modern-go_concurrent_LICENSE
cp vendor/github.com/modern-go/reflect2/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_modern-go_reflect2_LICENSE
cp vendor/github.com/mrunalp/fileutils/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_mrunalp_fileutils_LICENSE
cp vendor/github.com/mtrmac/gpgme/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_mtrmac_gpgme_LICENSE
cp vendor/github.com/nbutton23/zxcvbn-go/LICENSE.txt %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_nbutton23_zxcvbn-go_LICENSE.txt
cp vendor/github.com/onsi/ginkgo/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_onsi_ginkgo_LICENSE
cp vendor/github.com/onsi/ginkgo/reporters/stenographer/support/go-colorable/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_onsi_ginkgo_reporters_stenographer_support_go-colorable_LICENSE
cp vendor/github.com/onsi/ginkgo/reporters/stenographer/support/go-isatty/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_onsi_ginkgo_reporters_stenographer_support_go-isatty_LICENSE
cp vendor/github.com/onsi/gomega/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_onsi_gomega_LICENSE
cp vendor/github.com/opencontainers/go-digest/LICENSE.code %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_opencontainers_go-digest_LICENSE.code
cp vendor/github.com/opencontainers/go-digest/LICENSE.docs %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_opencontainers_go-digest_LICENSE.docs
cp vendor/github.com/opencontainers/image-spec/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_opencontainers_image-spec_LICENSE
cp vendor/github.com/opencontainers/runc/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_opencontainers_runc_LICENSE
cp vendor/github.com/opencontainers/runtime-spec/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_opencontainers_runtime-spec_LICENSE
cp vendor/github.com/opencontainers/runtime-tools/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_opencontainers_runtime-tools_LICENSE
cp vendor/github.com/opencontainers/selinux/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_opencontainers_selinux_LICENSE
cp vendor/github.com/openshift/imagebuilder/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_openshift_imagebuilder_LICENSE
cp vendor/github.com/openshift/imagebuilder/dockerfile/NOTICE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_openshift_imagebuilder_dockerfile_NOTICE
cp vendor/github.com/opentracing/opentracing-go/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_opentracing_opentracing-go_LICENSE
cp vendor/github.com/ostreedev/ostree-go/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_ostreedev_ostree-go_LICENSE
cp vendor/github.com/pelletier/go-toml/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_pelletier_go-toml_LICENSE
cp vendor/github.com/pkg/errors/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_pkg_errors_LICENSE
cp vendor/github.com/pmezard/go-difflib/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_pmezard_go-difflib_LICENSE
cp vendor/github.com/pquerna/ffjson/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_pquerna_ffjson_LICENSE
cp vendor/github.com/prometheus/client_golang/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_prometheus_client_golang_LICENSE
cp vendor/github.com/prometheus/client_golang/NOTICE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_prometheus_client_golang_NOTICE
cp vendor/github.com/prometheus/client_model/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_prometheus_client_model_LICENSE
cp vendor/github.com/prometheus/common/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_prometheus_common_LICENSE
cp vendor/github.com/prometheus/procfs/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_prometheus_procfs_LICENSE
cp vendor/github.com/russross/blackfriday/LICENSE.txt %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_russross_blackfriday_LICENSE.txt
cp vendor/github.com/seccomp/containers-golang/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_seccomp_containers-golang_LICENSE
cp vendor/github.com/seccomp/libseccomp-golang/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_seccomp_libseccomp-golang_LICENSE
cp vendor/github.com/sirupsen/logrus/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_sirupsen_logrus_LICENSE
cp vendor/github.com/soheilhy/cmux/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_soheilhy_cmux_LICENSE
cp vendor/github.com/sourcegraph/go-diff/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_sourcegraph_go-diff_LICENSE
cp vendor/github.com/spf13/afero/LICENSE.txt %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_spf13_afero_LICENSE.txt
cp vendor/github.com/spf13/cast/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_spf13_cast_LICENSE
cp vendor/github.com/spf13/cobra/LICENSE.txt %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_spf13_cobra_LICENSE.txt
cp vendor/github.com/spf13/jwalterweatherman/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_spf13_jwalterweatherman_LICENSE
cp vendor/github.com/spf13/pflag/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_spf13_pflag_LICENSE
cp vendor/github.com/spf13/viper/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_spf13_viper_LICENSE
cp vendor/github.com/syndtr/gocapability/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_syndtr_gocapability_LICENSE
cp vendor/github.com/tchap/go-patricia/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_tchap_go-patricia_LICENSE
cp vendor/github.com/timakin/bodyclose/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_timakin_bodyclose_LICENSE
cp vendor/github.com/ulikunitz/xz/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_ulikunitz_xz_LICENSE
cp vendor/github.com/urfave/cli/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_urfave_cli_LICENSE
cp vendor/github.com/vbatts/git-validation/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_vbatts_git-validation_LICENSE
cp vendor/github.com/vbatts/tar-split/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_vbatts_tar-split_LICENSE
cp vendor/github.com/vbauerster/mpb/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_vbauerster_mpb_LICENSE
cp vendor/github.com/vishvananda/netlink/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_vishvananda_netlink_LICENSE
cp vendor/github.com/vishvananda/netns/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_vishvananda_netns_LICENSE
cp vendor/github.com/xeipuuv/gojsonpointer/LICENSE-APACHE-2.0.txt %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_xeipuuv_gojsonpointer_LICENSE-APACHE-2.0.txt
cp vendor/github.com/xeipuuv/gojsonreference/LICENSE-APACHE-2.0.txt %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_xeipuuv_gojsonreference_LICENSE-APACHE-2.0.txt
cp vendor/github.com/xeipuuv/gojsonschema/LICENSE-APACHE-2.0.txt %{buildroot}/usr/share/package-licenses/cri-o/vendor_github.com_xeipuuv_gojsonschema_LICENSE-APACHE-2.0.txt
cp vendor/golang.org/x/crypto/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_golang.org_x_crypto_LICENSE
cp vendor/golang.org/x/net/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_golang.org_x_net_LICENSE
cp vendor/golang.org/x/oauth2/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_golang.org_x_oauth2_LICENSE
cp vendor/golang.org/x/sync/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_golang.org_x_sync_LICENSE
cp vendor/golang.org/x/sys/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_golang.org_x_sys_LICENSE
cp vendor/golang.org/x/text/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_golang.org_x_text_LICENSE
cp vendor/golang.org/x/time/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_golang.org_x_time_LICENSE
cp vendor/golang.org/x/tools/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_golang.org_x_tools_LICENSE
cp vendor/google.golang.org/appengine/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_google.golang.org_appengine_LICENSE
cp vendor/google.golang.org/genproto/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_google.golang.org_genproto_LICENSE
cp vendor/google.golang.org/grpc/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_google.golang.org_grpc_LICENSE
cp vendor/gopkg.in/fsnotify.v1/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_gopkg.in_fsnotify.v1_LICENSE
cp vendor/gopkg.in/inf.v0/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_gopkg.in_inf.v0_LICENSE
cp vendor/gopkg.in/square/go-jose.v2/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_gopkg.in_square_go-jose.v2_LICENSE
cp vendor/gopkg.in/square/go-jose.v2/json/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_gopkg.in_square_go-jose.v2_json_LICENSE
cp vendor/gopkg.in/tomb.v1/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_gopkg.in_tomb.v1_LICENSE
cp vendor/gopkg.in/yaml.v2/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_gopkg.in_yaml.v2_LICENSE
cp vendor/gopkg.in/yaml.v2/LICENSE.libyaml %{buildroot}/usr/share/package-licenses/cri-o/vendor_gopkg.in_yaml.v2_LICENSE.libyaml
cp vendor/gopkg.in/yaml.v2/NOTICE %{buildroot}/usr/share/package-licenses/cri-o/vendor_gopkg.in_yaml.v2_NOTICE
cp vendor/k8s.io/api/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_k8s.io_api_LICENSE
cp vendor/k8s.io/apiextensions-apiserver/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_k8s.io_apiextensions-apiserver_LICENSE
cp vendor/k8s.io/apimachinery/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_k8s.io_apimachinery_LICENSE
cp vendor/k8s.io/apiserver/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_k8s.io_apiserver_LICENSE
cp vendor/k8s.io/client-go/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_k8s.io_client-go_LICENSE
cp vendor/k8s.io/cloud-provider/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_k8s.io_cloud-provider_LICENSE
cp vendor/k8s.io/component-base/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_k8s.io_component-base_LICENSE
cp vendor/k8s.io/cri-api/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_k8s.io_cri-api_LICENSE
cp vendor/k8s.io/klog/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_k8s.io_klog_LICENSE
cp vendor/k8s.io/kube-openapi/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_k8s.io_kube-openapi_LICENSE
cp vendor/k8s.io/kubernetes/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_k8s.io_kubernetes_LICENSE
cp vendor/k8s.io/kubernetes/third_party/forked/golang/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_k8s.io_kubernetes_third_party_forked_golang_LICENSE
cp vendor/k8s.io/utils/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_k8s.io_utils_LICENSE
cp vendor/mvdan.cc/interfacer/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_mvdan.cc_interfacer_LICENSE
cp vendor/mvdan.cc/lint/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_mvdan.cc_lint_LICENSE
cp vendor/mvdan.cc/unparam/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_mvdan.cc_unparam_LICENSE
cp vendor/sigs.k8s.io/yaml/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_sigs.k8s.io_yaml_LICENSE
cp vendor/sourcegraph.com/sqs/pbtypes/LICENSE %{buildroot}/usr/share/package-licenses/cri-o/vendor_sourcegraph.com_sqs_pbtypes_LICENSE
%make_install PREFIX=%{buildroot}/usr
mkdir -p %{buildroot}/usr/lib/tmpfiles.d
install -m 0644 %{SOURCE1} %{buildroot}/usr/lib/tmpfiles.d/cri-o.conf
## install_append content
sed -i -e 's:local/::' ./contrib/systemd/crio-wipe.service
sed -i '8iStartLimitIntervalSec=120' ./contrib/systemd/crio.service
sed -i '9iStartLimitBurst=6'         ./contrib/systemd/crio.service
sed -i -e 's:local/::'               ./contrib/systemd/crio.service
sed -i '27iRestart=on-failure'       ./contrib/systemd/crio.service
sed -i '28iRestartSec=10'            ./contrib/systemd/crio.service
make install.completions PREFIX=%{buildroot}/usr
make install.systemd PREFIX=%{buildroot}/usr
install -D -m 644 crio.conf %{buildroot}/usr/share/defaults/crio/crio.conf
install -D -m 644 ./vendor/github.com/seccomp/containers-golang/seccomp.json %{buildroot}/usr/share/defaults/crio/seccomp.json
install -D -m 644 crio-umount.conf %{buildroot}/usr/share/defaults/crio/crio-umount.conf
install -D -m 644 policy.json %{buildroot}/usr/share/defaults/crio/policy.json
## install_append end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/crio

%files config
%defattr(-,root,root,-)
/usr/lib/tmpfiles.d/cri-o.conf

%files data
%defattr(-,root,root,-)
/usr/share/defaults/crio/crio-umount.conf
/usr/share/defaults/crio/crio.conf
/usr/share/defaults/crio/policy.json
/usr/share/defaults/crio/seccomp.json

%files libexec
%defattr(-,root,root,-)
/usr/libexec/crio/conmon
/usr/libexec/crio/crio-wipe/crio-wipe.bash
/usr/libexec/crio/crio-wipe/helpers.bash
/usr/libexec/crio/crio-wipe/lib.bash
/usr/libexec/crio/pause

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/cri-o/LICENSE
/usr/share/package-licenses/cri-o/logo_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_Azure_go-ansiterm_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_BurntSushi_toml_COPYING
/usr/share/package-licenses/cri-o/vendor_github.com_Microsoft_go-winio_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_Microsoft_go-winio_archive_tar_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_Microsoft_hcsshim_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_OpenPeeDeeP_depguard_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_VividCortex_ewma_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_beorn7_perks_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_blang_semver_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_checkpoint-restore_go-criu_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_containerd_console_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_containerd_containerd_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_containerd_continuity_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_containerd_fifo_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_containerd_go-runc_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_containerd_project_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_containerd_ttrpc_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_containerd_typeurl_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_containernetworking_cni_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_containernetworking_plugins_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_containers_buildah_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_containers_image_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_containers_libpod_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_containers_libpod_pkg_kubeutils_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_containers_psgo_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_containers_storage_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_containers_storage_NOTICE
/usr/share/package-licenses/cri-o/vendor_github.com_coreos_go-iptables_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_coreos_go-systemd_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_coreos_pkg_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_cpuguy83_go-md2man_LICENSE.md
/usr/share/package-licenses/cri-o/vendor_github.com_cri-o_ocicni_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_cyphar_filepath-securejoin_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_davecgh_go-spew_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_docker_distribution_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_docker_docker-credential-helpers_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_docker_docker_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_docker_docker_NOTICE
/usr/share/package-licenses/cri-o/vendor_github.com_docker_docker_pkg_symlink_LICENSE.APACHE
/usr/share/package-licenses/cri-o/vendor_github.com_docker_docker_pkg_symlink_LICENSE.BSD
/usr/share/package-licenses/cri-o/vendor_github.com_docker_go-connections_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_docker_go-metrics_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_docker_go-metrics_LICENSE.docs
/usr/share/package-licenses/cri-o/vendor_github.com_docker_go-units_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_docker_libnetwork_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_docker_libtrust_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_docker_spdystream_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_docker_spdystream_LICENSE.docs
/usr/share/package-licenses/cri-o/vendor_github.com_emicklei_go-restful_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_etcd-io_bbolt_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_fatih_color_LICENSE.md
/usr/share/package-licenses/cri-o/vendor_github.com_fsnotify_fsnotify_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_fsouza_go-dockerclient_DOCKER-LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_fsouza_go-dockerclient_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_ghodss_yaml_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_go-critic_go-critic_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_go-lintpack_lintpack_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_go-toolsmith_astcast_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_go-toolsmith_astcopy_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_go-toolsmith_astequal_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_go-toolsmith_astfmt_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_go-toolsmith_astp_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_go-toolsmith_strparse_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_go-toolsmith_typep_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_go-zoo_bone_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_gobwas_glob_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_godbus_dbus_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_gogo_protobuf_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_golang_groupcache_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_golang_mock_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_golang_protobuf_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_golangci_check_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_golangci_dupl_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_golangci_errcheck_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_golangci_go-misc_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_golangci_go-tools_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_golangci_go-tools_lint_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_golangci_go-tools_ssa_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_golangci_goconst_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_golangci_gocyclo_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_golangci_gofmt_gofmt_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_golangci_gofmt_goimports_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_golangci_golangci-lint_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_golangci_gosec_LICENSE.txt
/usr/share/package-licenses/cri-o/vendor_github.com_golangci_ineffassign_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_golangci_lint-1_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_golangci_maligned_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_golangci_misspell_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_golangci_prealloc_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_golangci_revgrep_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_golangci_unconvert_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_google_go-cmp_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_google_gofuzz_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_google_renameio_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_google_uuid_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_googleapis_gnostic_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_gorilla_mux_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_gostaticanalysis_analysisutil_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_hashicorp_errwrap_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_hashicorp_go-multierror_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_hashicorp_go-version_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_hashicorp_golang-lru_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_hashicorp_hcl_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_hpcloud_tail_LICENSE.txt
/usr/share/package-licenses/cri-o/vendor_github.com_hpcloud_tail_ratelimiter_Licence
/usr/share/package-licenses/cri-o/vendor_github.com_ijc_Gotty_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_imdario_mergo_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_inconshreveable_mousetrap_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_ishidawataru_sctp_GO_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_ishidawataru_sctp_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_json-iterator_go_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_kisielk_gotool_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_klauspost_compress_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_klauspost_compress_snappy_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_klauspost_compress_zstd_internal_xxhash_LICENSE.txt
/usr/share/package-licenses/cri-o/vendor_github.com_klauspost_cpuid_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_klauspost_pgzip_GO_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_klauspost_pgzip_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_konsorten_go-windows-terminal-sequences_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_kr_pty_License
/usr/share/package-licenses/cri-o/vendor_github.com_lithammer_dedent_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_magiconair_properties_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_mattn_go-colorable_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_mattn_go-isatty_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_mattn_go-shellwords_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_matttproud_golang_protobuf_extensions_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_mistifyio_go-zfs_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_mitchellh_go-homedir_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_mitchellh_mapstructure_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_modern-go_concurrent_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_modern-go_reflect2_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_mrunalp_fileutils_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_mtrmac_gpgme_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_nbutton23_zxcvbn-go_LICENSE.txt
/usr/share/package-licenses/cri-o/vendor_github.com_onsi_ginkgo_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_onsi_ginkgo_reporters_stenographer_support_go-colorable_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_onsi_ginkgo_reporters_stenographer_support_go-isatty_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_onsi_gomega_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_opencontainers_go-digest_LICENSE.code
/usr/share/package-licenses/cri-o/vendor_github.com_opencontainers_go-digest_LICENSE.docs
/usr/share/package-licenses/cri-o/vendor_github.com_opencontainers_image-spec_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_opencontainers_runc_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_opencontainers_runtime-spec_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_opencontainers_runtime-tools_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_opencontainers_selinux_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_openshift_imagebuilder_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_openshift_imagebuilder_dockerfile_NOTICE
/usr/share/package-licenses/cri-o/vendor_github.com_opentracing_opentracing-go_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_ostreedev_ostree-go_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_pelletier_go-toml_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_pkg_errors_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_pmezard_go-difflib_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_pquerna_ffjson_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_prometheus_client_golang_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_prometheus_client_golang_NOTICE
/usr/share/package-licenses/cri-o/vendor_github.com_prometheus_client_model_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_prometheus_common_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_prometheus_procfs_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_russross_blackfriday_LICENSE.txt
/usr/share/package-licenses/cri-o/vendor_github.com_seccomp_containers-golang_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_seccomp_libseccomp-golang_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_sirupsen_logrus_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_soheilhy_cmux_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_sourcegraph_go-diff_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_spf13_afero_LICENSE.txt
/usr/share/package-licenses/cri-o/vendor_github.com_spf13_cast_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_spf13_cobra_LICENSE.txt
/usr/share/package-licenses/cri-o/vendor_github.com_spf13_jwalterweatherman_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_spf13_pflag_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_spf13_viper_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_syndtr_gocapability_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_tchap_go-patricia_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_timakin_bodyclose_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_ulikunitz_xz_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_urfave_cli_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_vbatts_git-validation_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_vbatts_tar-split_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_vbauerster_mpb_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_vishvananda_netlink_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_vishvananda_netns_LICENSE
/usr/share/package-licenses/cri-o/vendor_github.com_xeipuuv_gojsonpointer_LICENSE-APACHE-2.0.txt
/usr/share/package-licenses/cri-o/vendor_github.com_xeipuuv_gojsonreference_LICENSE-APACHE-2.0.txt
/usr/share/package-licenses/cri-o/vendor_github.com_xeipuuv_gojsonschema_LICENSE-APACHE-2.0.txt
/usr/share/package-licenses/cri-o/vendor_golang.org_x_crypto_LICENSE
/usr/share/package-licenses/cri-o/vendor_golang.org_x_net_LICENSE
/usr/share/package-licenses/cri-o/vendor_golang.org_x_oauth2_LICENSE
/usr/share/package-licenses/cri-o/vendor_golang.org_x_sync_LICENSE
/usr/share/package-licenses/cri-o/vendor_golang.org_x_sys_LICENSE
/usr/share/package-licenses/cri-o/vendor_golang.org_x_text_LICENSE
/usr/share/package-licenses/cri-o/vendor_golang.org_x_time_LICENSE
/usr/share/package-licenses/cri-o/vendor_golang.org_x_tools_LICENSE
/usr/share/package-licenses/cri-o/vendor_google.golang.org_appengine_LICENSE
/usr/share/package-licenses/cri-o/vendor_google.golang.org_genproto_LICENSE
/usr/share/package-licenses/cri-o/vendor_google.golang.org_grpc_LICENSE
/usr/share/package-licenses/cri-o/vendor_gopkg.in_fsnotify.v1_LICENSE
/usr/share/package-licenses/cri-o/vendor_gopkg.in_inf.v0_LICENSE
/usr/share/package-licenses/cri-o/vendor_gopkg.in_square_go-jose.v2_LICENSE
/usr/share/package-licenses/cri-o/vendor_gopkg.in_square_go-jose.v2_json_LICENSE
/usr/share/package-licenses/cri-o/vendor_gopkg.in_tomb.v1_LICENSE
/usr/share/package-licenses/cri-o/vendor_gopkg.in_yaml.v2_LICENSE
/usr/share/package-licenses/cri-o/vendor_gopkg.in_yaml.v2_LICENSE.libyaml
/usr/share/package-licenses/cri-o/vendor_gopkg.in_yaml.v2_NOTICE
/usr/share/package-licenses/cri-o/vendor_k8s.io_api_LICENSE
/usr/share/package-licenses/cri-o/vendor_k8s.io_apiextensions-apiserver_LICENSE
/usr/share/package-licenses/cri-o/vendor_k8s.io_apimachinery_LICENSE
/usr/share/package-licenses/cri-o/vendor_k8s.io_apiserver_LICENSE
/usr/share/package-licenses/cri-o/vendor_k8s.io_client-go_LICENSE
/usr/share/package-licenses/cri-o/vendor_k8s.io_cloud-provider_LICENSE
/usr/share/package-licenses/cri-o/vendor_k8s.io_component-base_LICENSE
/usr/share/package-licenses/cri-o/vendor_k8s.io_cri-api_LICENSE
/usr/share/package-licenses/cri-o/vendor_k8s.io_klog_LICENSE
/usr/share/package-licenses/cri-o/vendor_k8s.io_kube-openapi_LICENSE
/usr/share/package-licenses/cri-o/vendor_k8s.io_kubernetes_LICENSE
/usr/share/package-licenses/cri-o/vendor_k8s.io_kubernetes_third_party_forked_golang_LICENSE
/usr/share/package-licenses/cri-o/vendor_k8s.io_utils_LICENSE
/usr/share/package-licenses/cri-o/vendor_mvdan.cc_interfacer_LICENSE
/usr/share/package-licenses/cri-o/vendor_mvdan.cc_lint_LICENSE
/usr/share/package-licenses/cri-o/vendor_mvdan.cc_unparam_LICENSE
/usr/share/package-licenses/cri-o/vendor_sigs.k8s.io_yaml_LICENSE
/usr/share/package-licenses/cri-o/vendor_sourcegraph.com_sqs_pbtypes_LICENSE

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man5/crio.conf.5
/usr/share/man/man8/crio.8

%files services
%defattr(-,root,root,-)
/usr/lib/systemd/system/cri-o.service
/usr/lib/systemd/system/crio-shutdown.service
/usr/lib/systemd/system/crio-wipe.service
/usr/lib/systemd/system/crio.service
